### ISSUE TITLE
(Postgrex.Error) FATAL 53300 (too_many_connections) too many connections for role

### ISSUE THREAD

**Issue by axelclark** [axelclark/golf#70]
```bash
2018-12-26T20:29:28.271894+00:00 golf[golf-6555d96594-k49ft]: web.1  | 20:29:28.271 [error] Postgrex.Protocol (#PID<0.2200.0>) failed to connect: ** 
(Postgrex.Error) FATAL 53300 (too_many_connections) too many connections for role "399261c3-bcb8-40f4-b2f1-3599b3c836a5-user"

```

**Comment by axelclark** [comment]
```
2018-12-26T20:55:10.540785+00:00 golf[golf-58bd677487-r259g]: web.1  | 20:55:10.540 request_id=2lpvqpdu1hs1k5ko5g000751 [info] POST /session
2018-12-26T20:55:10.541295+00:00 golf[golf-58bd677487-r259g]: web.1  | 20:55:10.540 request_id=2lpvqpdu1hs1k5ko5g000751 [info] Sent 302 in 595µs
2018-12-26T20:55:10.620171+00:00 golf[golf-58bd677487-r259g]: web.1  | 20:55:10.619 request_id=2lpvqpe2o1p3rivae8000761 [info] GET /
2018-12-26T20:55:10.624953+00:00 golf[golf-58bd677487-r259g]: web.1  | 20:55:10.624 request_id=2lpvqpe2o1p3rivae8000761 [info] Sent 200 in 5ms
2018-12-26T20:55:14.788954+00:00 golf[golf-58bd677487-r259g]: web.1  | 20:55:14.788 request_id=2lpvqplr7nmoe2n84o000771 [info] GET /rounds
2018-12-26T20:55:14.898674+00:00 golf[golf-58bd677487-r259g]: web.1  | 20:55:14.898 request_id=2lpvqplr7nmoe2n84o000771 [info] Sent 200 in 110ms
2018-12-26T20:55:15.264103+00:00 golf[golf-bd4f6b664-zdxdg]: web.1  | 20:55:15.262 [info] CONNECT GolfWeb.UserSocket
2018-12-26T20:55:15.264120+00:00 golf[golf-bd4f6b664-zdxdg]: web.1  |   Transport: :websocket
2018-12-26T20:55:15.264150+00:00 golf[golf-bd4f6b664-zdxdg]: web.1  |   Connect Info: %{}
2018-12-26T20:55:15.264202+00:00 golf[golf-bd4f6b664-zdxdg]: web.1  |   Parameters: %{"__client_id" => "cf00dbf8-7961-4925-aac0-b1b25c5cff60", "__client_lib_version" => "15", "__drab_return" => "SFMyNTY.g3QAAAACZAAEZGF0YWwAAAAFaAJkAApjb250cm9sbGVyZAAeRWxpeGlyLkdvbGZXZWIuUm91bmRDb250cm9sbGVyaAJkAAljb21tYW5kZXJkAB1FbGl4aXIuR29sZldlYi5Sb3VuZENvbW1hbmRlcmgCZAAEdmlld2QAGEVsaXhpci5Hb2xmV2ViLlJvdW5kVmlld2gCZAAGYWN0aW9uZAAFaW5kZXhoAmQAB2Fzc2lnbnNqamQABnNpZ25lZG4GAMfKTOxnAQ.XTrQs1yjtevy1RgDCdDw2TExJKn7ybisIPIv1xPx600", "vsn" => "2.0.0"}
2018-12-26T20:55:15.267669+00:00 golf[golf-bd4f6b664-zdxdg]: web.1  | 20:55:15.267 [info] Replied GolfWeb.UserSocket :ok
2018-12-26T20:55:15.328177+00:00 golf[golf-bd4f6b664-zdxdg]: web.1  | 20:55:15.327 [info] JOIN "__drab:same_path:/rounds" to Drab.Channel
2018-12-26T20:55:15.328300+00:00 golf[golf-bd4f6b664-zdxdg]: web.1  |   Transport:  :websocket
2018-12-26T20:55:15.328379+00:00 golf[golf-bd4f6b664-zdxdg]: web.1  |   Serializer: Phoenix.Socket.V2.JSONSerializer
2018-12-26T20:55:15.328443+00:00 golf[golf-bd4f6b664-zdxdg]: web.1  |   Parameters: %{}
2018-12-26T20:55:15.328505+00:00 golf[golf-bd4f6b664-zdxdg]: web.1  | 20:55:15.328 [info] Replied __drab:same_path:/rounds :ok
2018-12-26T20:55:15.381567+00:00 golf[golf-bd4f6b664-zdxdg]: web.1  | 
2018-12-26T20:55:15.381645+00:00 golf[golf-bd4f6b664-zdxdg]: web.1  |     Started Drab for __drab:same_path:/rounds, handling events in GolfWeb.RoundCommander
2018-12-26T20:55:15.381659+00:00 golf[golf-bd4f6b664-zdxdg]: web.1  |     You may debug Drab functions in IEx by copy/paste the following:
2018-12-26T20:55:15.381744+00:00 golf[golf-bd4f6b664-zdxdg]: web.1  | import Drab.{Modal, Element, Live, Core}
2018-12-26T20:55:15.381885+00:00 golf[golf-bd4f6b664-zdxdg]: web.1  | socket = Drab.get_socket(pid("0.2374.0"))
2018-12-26T20:55:15.382275+00:00 golf[golf-bd4f6b664-zdxdg]: web.1  | 
2018-12-26T20:55:15.382391+00:00 golf[golf-bd4f6b664-zdxdg]: web.1  |     Examples:
2018-12-26T20:55:15.382454+00:00 golf[golf-bd4f6b664-zdxdg]: web.1  | socket |> alert("Title", "Sure?", buttons: [ok: "Azaliż", cancel: "Poniechaj"])
2018-12-26T20:55:15.382513+00:00 golf[golf-bd4f6b664-zdxdg]: web.1  | socket |> set_style("body", backgroundColor: "red")
2018-12-26T20:55:15.382569+00:00 golf[golf-bd4f6b664-zdxdg]: web.1  | socket |> poke(text: "This assign has been drabbed!")
2018-12-26T20:55:15.382593+00:00 golf[golf-bd4f6b664-zdxdg]: web.1  | socket |> exec_js("alert('hello from IEx!')")
2018-12-26T20:55:15.382650+00:00 golf[golf-bd4f6b664-zdxdg]: web.1  | 
2018-12-26T20:55:16.777507+00:00 golf[golf-bd4f6b664-zdxdg]: web.1  | 20:55:16.777 [error] Postgrex.Protocol (#PID<0.2199.0>) failed to connect: ** (Postgrex.Error) FATAL 53300 (too_many_connections) too many connections for role "399261c3-bcb8-40f4-b2f1-3599b3c836a5-user"
2018-12-26T20:55:18.559787+00:00 golf[golf-bd4f6b664-zdxdg]: web.1  | 20:55:18.559 [error] Postgrex.Protocol (#PID<0.2198.0>) failed to connect: ** (Postgrex.Error) FATAL 53300 (too_many_connections) too many connections for role "399261c3-bcb8-40f4-b2f1-3599b3c836a5-user"
2018-12-26T20:55:23.359560+00:00 golf[golf-bd4f6b664-zdxdg]: web.1  | 20:55:23.359 request_id=2lpvqq5q3ftsq6ab7s000001 [info] GET /courses
2018-12-26T20:55:23.366128+00:00 golf[golf-bd4f6b664-zdxdg]: web.1  | 20:55:23.365 request_id=2lpvqq5q3ftsq6ab7s000001 [info] Sent 302 in 6ms
2018-12-26T20:55:23.433214+00:00 golf[golf-58bd677487-r259g]: web.1  | 20:55:23.432 request_id=2lpvqq5uenl87qnbgk000901 [info] GET /session/new
2018-12-26T20:55:23.433235+00:00 golf[golf-58bd677487-r259g]: web.1  | 20:55:23.432 request_id=2lpvqq5uenl87qnbgk000901 [info] Sent 302 in 505µs
2018-12-26T20:55:23.664570+00:00 golf[golf-bd4f6b664-zdxdg]: web.1  | 20:55:23.663 request_id=2lpvqq66le2mc2b290000022 [info] GET /
2018-12-26T20:55:23.664688+00:00 golf[golf-bd4f6b664-zdxdg]: web.1  | 20:55:23.664 request_id=2lpvqq66le2mc2b290000022 [info] Sent 302 in 439µs
2018-12-26T20:55:23.723382+00:00 golf[golf-bd4f6b664-zdxdg]: web.1  | 20:55:23.722 request_id=2lpvqq6fp9uka1mlr0000011 [info] GET /session/new
2018-12-26T20:55:23.725230+00:00 golf[golf-bd4f6b664-zdxdg]: web.1  | 20:55:23.724 request_id=2lpvqq6fp9uka1mlr0000011 [info] Sent 200 in 1ms
2018-12-26T20:55:26.020006+00:00 golf[golf-bd4f6b664-zdxdg]: web.1  | 20:55:26.019 request_id=2lpvqqaolsdhor6400000021 [info] POST /session
2018-12-26T20:55:28.155739+00:00 golf[golf-bd4f6b664-zdxdg]: web.1  | 20:55:28.154 [error] Postgrex.Protocol (#PID<0.2199.0>) failed to connect: ** (Postgrex.Error) FATAL 53300 (too_many_connections) too many connections for role "399261c3-bcb8-40f4-b2f1-3599b3c836a5-user"
2018-12-26T20:55:28.810143+00:00 golf[golf-bd4f6b664-zdxdg]: web.1  | 20:55:28.809 request_id=2lpvqqaolsdhor6400000021 [info] Converted error DBConnection.ConnectionError to 500 response
2018-12-26T20:55:28.810292+00:00 golf[golf-bd4f6b664-zdxdg]: web.1  | 20:55:28.809 request_id=2lpvqqaolsdhor6400000021 [info] Sent 500 in 2790ms
2018-12-26T20:55:28.864748+00:00 golf[golf-bd4f6b664-zdxdg]: web.1  | 20:55:28.864 [error] #PID<0.2388.0> running GolfWeb.Endpoint (connection #PID<0.2387.0>, stream id 1) terminated
2018-12-26T20:55:28.864805+00:00 golf[golf-bd4f6b664-zdxdg]: web.1  | Server: golf.gigalixirapp.com:80 (http)
2018-12-26T20:55:28.864882+00:00 golf[golf-bd4f6b664-zdxdg]: web.1  | Request: POST /session?request_path=%2F
2018-12-26T20:55:28.864990+00:00 golf[golf-bd4f6b664-zdxdg]: web.1  | ** (exit) an exception was raised:
2018-12-26T20:55:28.865071+00:00 golf[golf-bd4f6b664-zdxdg]: web.1  |     ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 2789ms
2018-12-26T20:55:28.865127+00:00 golf[golf-bd4f6b664-zdxdg]: web.1  |         (ecto_sql) lib/ecto/adapters/sql.ex:595: Ecto.Adapters.SQL.raise_sql_call_error/1
2018-12-26T20:55:28.865616+00:00 golf[golf-bd4f6b664-zdxdg]: web.1  |         (ecto_sql) lib/ecto/adapters/sql.ex:528: Ecto.Adapters.SQL.execute/5
2018-12-26T20:55:28.865688+00:00 golf[golf-bd4f6b664-zdxdg]: web.1  |         (ecto) lib/ecto/repo/queryable.ex:147: Ecto.Repo.Queryable.execute/4
2018-12-26T20:55:28.865906+00:00 golf[golf-bd4f6b664-zdxdg]: web.1  |         (ecto) lib/ecto/repo/queryable.ex:18: Ecto.Repo.Queryable.all/3
2018-12-26T20:55:28.866080+00:00 golf[golf-bd4f6b664-zdxdg]: web.1  |         (ecto) lib/ecto/repo/queryable.ex:66: Ecto.Repo.Queryable.one/3
2018-12-26T20:55:28.866142+00:00 golf[golf-bd4f6b664-zdxdg]: web.1  |         (pow) lib/pow/ecto/context.ex:100: Pow.Ecto.Context.authenticate/2
2018-12-26T20:55:28.866201+00:00 golf[golf-bd4f6b664-zdxdg]: web.1  |         (pow) lib/pow/plug.ex:82: Pow.Plug.authenticate_user/2
2018-12-26T20:55:28.866224+00:00 golf[golf-bd4f6b664-zdxdg]: web.1  |         (pow) lib/pow/phoenix/controllers/controller.ex:89: Pow.Phoenix.Controller.action/3
2018-12-26T20:55:37.044078+00:00 golf[golf-bd4f6b664-zdxdg]: web.1  | 20:55:37.043 [error] Postgrex.Protocol (#PID<0.2198.0>) failed to connect: ** (Postgrex.Error) FATAL 53300 (too_many_connections) too many connections for role "399261c3-bcb8-40f4-b2f1-3599b3c836a5-user"
2018-12-26T20:55:48.768760+00:00 golf[golf-bd4f6b664-zdxdg]: web.1  | 20:55:48.768 [error] Postgrex.Protocol (#PID<0.2198.0>) failed to connect: ** (Postgrex.Error) FATAL 53300 (too_many_connections) too many connections for role "399261c3-bcb8-40f4-b2f1-3599b3c836a5-user"
2018-12-26T20:55:56.775138+00:00 golf[golf-bd4f6b664-zdxdg]: web.1  | 20:55:56.774 [error] Postgrex.Protocol (#PID<0.2199.0>) failed to connect: ** (Postgrex.Error) FATAL 53300 (too_many_connections) too many connections for role "399261c3-bcb8-40f4-b2f1-3599b3c836a5-user"
2018-12-26T20:56:08.273812+00:00 golf[golf-bd4f6b664-zdxdg]: web.1  | 20:56:08.273 [error] Postgrex.Protocol (#PID<0.2198.0>) failed to connect: ** (Postgrex.Error) FATAL 53300 (too_many_connections) too many connections for role "399261c3-bcb8-40f4-b2f1-3599b3c836a5-user"
2018-12-26T20:56:12.573658+00:00 golf[golf-bd4f6b664-zdxdg]: web.1  | 20:56:12.573 [error] Postgrex.Protocol (#PID<0.2199.0>) failed to connect: ** (Postgrex.Error) FATAL 53300 (too_many_connections) too many connections for role "399261c3-bcb8-40f4-b2f1-3599b3c836a5-user"
2018-12-26T20:56:36.026050+00:00 golf[golf-bd4f6b664-zdxdg]: web.1  | 20:56:36.025 [error] Postgrex.Protocol (#PID<0.2198.0>) failed to connect: ** (Postgrex.Error) FATAL 53300 (too_many_connections) too many connections for role "399261c3-bcb8-40f4-b2f1-3599b3c836a5-user"
2018-12-26T20:56:42.093648+00:00 golf[golf-bd4f6b664-zdxdg]: web.1  | 20:56:42.093 [error] Postgrex.Protocol (#PID<0.2199.0>) failed to connect: ** (Postgrex.Error) FATAL 53300 (too_many_connections) too many connections for role "399261c3-bcb8-40f4-b2f1-3599b3c836a5-user"
```

**Comment by axelclark** [comment]
Fixed after:
> Hey Axel, I looked into it and it looks like you had several versions of your app all running at the same time. This was due to a bug we introduced a few days ago that has since been corrected, but it looks like your app still hadn't healed itself yet. It should be healed now and it looks like the errors have gone away. Lemme know if you still see it.
